const a = [
  'some',
  'a bitter,',
  'the',
  'the time you met a',
  'a',
  'the death of a',
  'the other',
  'a former',
  'an evil,',
  'a surprisingly',
  'a small-town,',
  'a famous,',
  'an exceptionally',
  'a spy posing as a',
  'a hopelessly',
  'the secret life of a',
  'your cousin, the',
  'the downfall of a',
  'the dark side of a',
  'the special talent of a',
  'a friendly,',
  'a soon-to-be',
  'a cool,',
  'your run-in with a',
  'a nerdy,',
  'a car accident caused by a',
  'a futuristic',
  'your ancestor, the',
  'an unreliable,',
  'a political scandal featuring a',
  'a professional',
  'a PR nightmare caused by a',
  'an extremely',
  'trying to sell a car to a',
  'the hijinks of a',
  'a dangerously',
  'an undercover,',
  'the career failure of a',
  'the diary of a',
  'the magical journey of a',
  'an alien undercover as a',
  'someone you met in a haunted forest. They were a',
  'how you used to be a',
  'the ghost of a'
]

const b = [
  'blonde',
  'hideous',
  'brave',
  'lazy',
  'clever',
  'mentally-unwell',
  'conniving',
  'party-going',
  'guilt-ridden',
  'forgetful',
  'rude',
  'camo-wearing',
  'casual',
  'basement-dwelling',
  'traumatized',
  'heartless',
  'house-bound',
  'cringey',
  'gifted',
  'homeless',
  'radical',
  'lost',
  'fashionable',
  'surprisingly wholesome',
  'elegant',
  'young',
  'polite',
  'terrified',
  'quiet',
  'skittish',
  'gay',
  'French',
  'republican',
  'well-read',
  'democratic',
  'methodical',
  'far-right',
  'drug-addicted',
  'far-left',
  'world-champion',
  'narcissistic',
  'stuck-in-the-past',
  'granola-munching',
  'bigoted',
  'social',
  'hypocritical',
  'confident',
  'cursed',
  'mentally-unstable',
  'possessed',
  'cowardly',
  'gunslinging',
  'sheepish',
  'constipated',
  'toxically optimistic',
  'reckless',
  'well-connected',
  'wounded',
  'rich',
  'picky',
  'poor',
  'magical',
  'gloomy',
  'toxic',
  'smug',
  'homely',
  'lucky',
  'cocky',
  'stinky',
  'FBI agent',
  'compassionate',
  'thief',
  'peaceful',
  'virtual-reality',
  'soft-spoken',
  'gorgeous',
  'workaholic',
  'goth',
  'old',
  'frantic',
  'grouchy',
  'wealthy',
  'stubborn',
  'suspicious',
  'bubbly'
]

const c = [
  'bartender',
  'door-to-door vitamin seller',
  'engineer',
  'armored truck driver',
  'librarian',
  'soldier',
  'elementary school teacher',
  'lunch lady',
  'graphic designer',
  'superhero',
  'small business owner',
  'monster truck driver',
  'stay-at-home mom',
  'corn farmer',
  'nurse',
  'documentary producer',
  'dog trainer',
  'lifestyle blogger',
  'astronaut',
  'chef',
  'janitor',
  'celebrity agent',
  'guy',
  'cave diver',
  'gal',
  'lifeguard',
  'grandma',
  'social media addict',
  'grandpa',
  'father of nine girls',
  'pet hoarder',
  'koala breeder',
  'pilot',
  'exotic animal smuggler',
  'cynic',
  'politician',
  'olympic swimmer',
  'art student',
  'ballet teacher',
  'paramedic',
  'pianist',
  'hypochondriac',
  'detective',
  'forest nymph',
  'police officer',
  'cyclops',
  'construction worker',
  'wrestling champion',
  'intern',
  'Mars colonist',
  'college student',
  'tax collector',
  'mechanic',
  'wizard',
  'cosmetologist',
  'child prodigy',
  'author',
  'dragon slayer',
  'journalist',
  'elf',
  'assistant manager',
  'sorcerer',
  'grocery clerk',
  'troll',
  'priest',
  'humanoid robot',
  'IT specialist',
  'spaceship mechanic',
  'homeless man',
  'wormhole explorer',
  'secretary',
  'time traveler',
  'teenager',
  'cowgirl',
  'firefighter',
  'clown',
  'lawyer',
  'underwater basket weaver',
  'drug dealer',
  'centaur',
  'middle school teacher',
  'ticket taker',
  'programmer',
  'juror',
  'florist',
  'brain surgeon',
  'stay-at-home dad',
  'life coach',
  'singer-songwriter',
  'kidnapper',
  'movie star',
  'mail carrier',
  'runner',
  'train conductor',
  'serial killer',
  'retail employee',
  'door-to-door salesman',
  'talking horse',
  'football player',
  'shuttle driver',
  'comic strip author',
  'ancient god',
  'babysitter',
  'magician',
  'street vendor',
  'sewer troll'
]

const d = [
  'who hides from the police',
  'who vandalizes a famous painting',
  'who runs away from home',
  'who forgets where they live',
  'who has to find a new job',
  'who gets stuck in a cardboard bailer',
  'who never leaves their house',
  'who drops out of a GED prep class',
  'who gets out of jail',
  'who joins a convent',
  'who paints horrible modern art',
  'who finds themselves in a sinking submarine',
  'who moonlights as a parking attendant',
  'who climbs Mount Everest every year',
  'who buys a used school bus',
  'who gets involved with a drug cartel',
  'who starts selling stolen car parts',
  'who refuses to listen to hip hop',
  'who kills their neighbor',
  'who starts a charity to cure smallpox',
  'who adopts a 15-year-old from Alaska',
  'who fakes their own death',
  'who throws away their life savings',
  'who robs a grocery store',
  'who eats only bananas for a month',
  'who comes back to life',
  'who is trapped in a box',
  'who tries to sneak onto an evacuation rocket',
  'who goes to community college',
  'who switches bodies with their dad',
  'who gets in a fight in a mysterious van',
  'who is cursed to say everything on their mind',
  'who gives advice to at-risk teens',
  'who tries to escape the afterlife',
  'who has to memorize the Bible',
  'who learns how to talk to animals',
  'who reports their spouse as missing',
  'who has to convince their neighbor their house is haunted',
  'who starts a job making potato chips',
  'who gets caught in an awkward love triangle',
  'who finds their true love',
  'who falls into a vat of baked beans',
  'who forms an addiction to simple syrup',
  'who forms an addiction to online shopping',
  'who builds houses for the homeless',
  'who turns into a mythical creature',
  'who starts eating paper clips',
  'who runs a money-laundering scheme',
  'who gets stuck in a closet at work',
  'who sells their soul in the classifieds',
  'who invents a cure to a disease',
  'who hijacks a public bus',
  'who finds a secret hidden treasure',
  'who falls in love with their enemy’s daughter',
  'who rents a minivan',
  'who finds irrefutable evidence of alien life',
  'who hires 20 underage employees',
  'who becomes a stand-up comedian',
  'who joins a civil rights campaign',
  'who convinces people they have magic powers',
  'who has to flee the country',
  'who gets revenge on an old romantic partner',
  'who starts a plague',
  'who turns an old closet into an interdimensional portal',
  'who sneaks into a cereal factory',
  'who gets in a fight with a cashier',
  'who adopts eight kittens',
  'who discovers their enemy turned them into a rabbit',
  'who knits sweaters laced with poison',
  'who lives the plot of a Dr. Seuss book',
  'who is in the most dangerous city in the world',
  'who wakes up locked in a high school bathroom',
  'who finds a buried ancient society',
  'who hires a rocket to the moon',
  'who impersonates a famous musician',
  'who sues the pizza delivery company',
  'who impulsively starts the wave at sport games',
  'who lives an entire day in reverse',
  'who surprises their spouse with a dead mouse',
  'who sells horrible poetry on public transit',
  'who joins a 10-piece brass band',
  'who buries an enormous sum of money',
  'who sells their soul to a jewelry store',
  'who spends a week inside a Taco Bell refrigerator',
  'who asks a clown on a date',
  'who throws a dead body in a lake',
  'who is pretending to be a robot',
  'who tries to visit Obama at his home',
  'who joins an extreme religious cult',
  'who sets six gerbils free in a park'
]

const e = [
  'to save money',
  'to fix their bad credit score',
  'because of a dark past',
  'after discovering an enchanted orb',
  'because of a secret terrorist plot',
  '… until an evil power changes everything',
  'because there was an alien invasion',
  'because of scheduling conflicts',
  'thanks to childhood trauma',
  'to save their worst enemy’s life',
  'to impress their dead parents',
  'as an elaborate ploy to make friends',
  'because of a bet placed years ago',
  'despite everyone telling them not to',
  'out of an abundance of caution',
  'as an extreme form of method acting',
  'while avoiding a suspicious-looking gentleman',
  'to stall a court hearing',
  'in an effort to pay off a debt',
  'after looking themselves up online',
  'without consulting their therapist',
  'but the narrator gets some of the details wrong',
  'because their best friend is evil',
  'after drinking a funny looking soda',
  'with ulterior motives',
  'to win back their true love',
  'after winning the lottery',
  'as a political stunt',
  'under suspicious circumstances',
  'to get intelligence for a foreign military',
  'with the help of an imaginary friend',
  'with the help of off-brand energy drinks',
  'for charity',
  'and blames it on a mid-life crisis',
  'for a tax write-off',
  'because nobody would take them seriously otherwise',
  'even though they have a cold',
  'to prevent an ancient prophecy from being fulfilled',
  'despite their spouse telling them not to',
  'to have something interesting for their memoir',
  'despite their dreams of being a polar bear',
  'in an obscure village in central Brazil',
  'without getting caught',
  'as a form of protest',
  'to impress their crush',
  'to rebel against societal norms',
  'while listening to 90s rap music',
  'without realizing they are being followed',
  'due to undiagnosed mental conditions',
  'and has to explain it to a judge',
  'after hitting their head on a filing cabinet',
  'due to an interplanetary disturbance',
  'while screaming obscenities',
  'to disguise their true magic powers',
  'in a moment of weakness',
  'to hide from the mafia',
  'to pass a high-school class from years ago'
]

function makePrompt(): string[] {
  const i0 = a[~~(Math.random() * a.length)]
  const i1 = b[~~(Math.random() * b.length)]
  const i2 = c[~~(Math.random() * c.length)]
  const i3 = d[~~(Math.random() * d.length)]
  const i4 = e[~~(Math.random() * e.length)]

  // // log the lengths of the arrays
  // console.log(`a.length: ${a.length}; b.length: ${b.length}; c.length: ${c.length}; d.length: ${d.length}; e.length: ${e.length}`);
  // console.log(`Total: ${a.length + b.length + c.length + d.length + e.length}`)
  // console.log(`Product: ${a.length * b.length * c.length * d.length * e.length}`);

  const prompt = [i0, i1, i2, i3, i4]
  return prompt
}

function getCombinations(): number {
  return a.length * b.length * c.length * d.length * e.length
}

// export default makePrompt;
export { makePrompt, getCombinations }
